######################################################
#Node Exporter metrics to Prometheus Monitoring Server
######################################################

apiVersion: v1
kind: Service
metadata:
  name: node-exporter-lb
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus-node-exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
